export const Types = {
    LOGIN: 'LOGIN',
    ADD_USER: 'ADD_USER',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    FORM_SUBMISSION_STATUS: 'FORM_SUBMISSION_STATUS',
    LOG_OUT_CURRENT_USER :'LOG_OUT_CURRENT_USER'
}